### ISSUE TITLE
library with UX inside the Demo

### ISSUE THREAD

**Issue by galvanu** [hodgef/ts-library-boilerplate-basic#83]
Thanks for the great starter project.
I want to use this project to develop a js library which also manipulates the UX (for examples renders some bubbles and so).
In order to do so I want to extend the demo project to be more dynamic.

For example, having html and even to be in react, so I can test it and do some more dynamic stuff with my library.
Can you help me with this request? how can I extend it to be supported?

**Comment by hodgef** [comment]
Hey @galvanu, sorry I didn't see this issue before.

Have you figured out how to integrate React? Let me know if you still need assistance with this and I'll reopen the ticket.

Regards,
Francisco Hodge
